version: '3.10'
services:
  mysql:
    container_name: mysql-sample
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - "./docker/data/mysql:/docker-entrypoint-initdb.d"
  postgresql:
    container_name: postgresql-sample
    image: postgres:latest
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432"
    volumes:
      - "./docker/data/postgresql:/docker-entrypoint-initdb.d"
