version: '3.8'

services:
  db:
    container_name: practice
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mywork
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
    volumes:  # initialize database
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306